# Generated by Django 4.0.5 on 2022-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_or_receiver', models.CharField(max_length=8)),
                ('email_id', models.CharField(max_length=255)),
            ],
        ),
    ]
